### ISSUE TITLE
rename 8.6 tag to 0.8.6

### ISSUE THREAD

**Issue by pabs3** [RaRe-Technologies/gensim#2948]
#### Problem description

There is a tag "8.6" in the repository that is between 0.8.7 and 0.8.5 in terms of when it was created, but it is missing the 0 at the start.

#### Steps/code/corpus to reproduce

```
git clone https://github.com/RaRe-Technologies/gensim.git
cd gensim
git tag | grep -v '^[0-3]'
```

Or load the github tags page:

https://github.com/RaRe-Technologies/gensim/tags?after=0.8.9

#### Versions

0.8.6

#### Suggested fix

```
git tag 0.8.6 8.6
git tag -d 8.6
git push --delete origin 8.6
git push --tags
```

**Comment by mpenkov** [comment]
Done, thank you for including a suggested fix!

**Comment by pabs3** [comment]
@mpenkov looks like this weird 8.6 tag has re-appeared, although the 0.8.6 tag still exists. Could you delete the 8.6 tag again and try to figure out why it came back?

**Comment by mpenkov** [comment]
@piskvorky @gojomo Could you guys please check that your local clones do not have an 8.6 tag? I suspect one of us has this tag lying around somewhere, and pushes it upstream occasionally.

Nobody else is able to push to upstream (right?) so I think it's one of us, anyway. I'll check my other machines for traces of this tag, too.

**Comment by pabs3** [comment]
@mpenkov @piskvorky @gojomo I noticed that the bogus 8.6 tag has been reintroduced, please remove it again. The correct `0.8.6` tag is still present though. Please run these commands again on all of the systems where gensim developers push to the repo:

```
git tag -d 8.6
git push --delete origin 8.6
```

**Comment by mpenkov** [comment]
@pabs3 Why does this matter to you?

**Comment by pabs3** [comment]
The `8.6` tag is clearly incorrect and it is strange that it keeps showing up despite getting deleted.

I'm in the process of packaging gensim and its dependencies for [Debian](https://www.debian.org/) so that my employer can use them. Part of the Debian package is the `debian/watch` file, which enables Debian to automatically check for newer versions of gensim. The `8.6` tag sorts newer than the other tags such as `4.1.2`, so the [uscan](https://manpages.debian.org/uscan) tool that Debian uses to check upstream versions will always find the bogus `8.6` tag instead of the actual latest tag. I've worked around this in the `debian/watch` file by making the regex not find `8.6` but it would be nice if I could remove the workaround so that if you do eventually make a real `8.6` tag, the watch file will find it.

**Comment by mpenkov** [comment]
Yeah, I agree that it is strange. I'm not sure why it keeps reappearing. I suppose we could set up a workflow that notifies us whenever it gets pushed (and maybe even by whom) - it's just that dealing with this requires an amount of effort that is not proportional to the severity of the issue.

**Comment by pabs3** [comment]
Fair enough. I'll stick with the hacky regex for now.
When you reach version series 8 you might need to skip 8.6 :)

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I see the tag got removed again and hasn't come back, thanks for that!

**Comment by mpenkov** [comment]
@piskvorky We should have mentioned that in the release notes, e.g. "killed phantom 8.6 tag with fire"
